### ISSUE TITLE
ameliorer l'auto player

### ISSUE THREAD

**Issue by HassanFadde** [HassanFadde/XO_auto_player#1]
il faut stocker les position d'ennemie pour appliquer la stratégie non pas les cases vides

**Comment by HassanFadde** [comment]
> il faut stocker les position d'ennemie pour appliquer la stratégie non pas les cases vides

je peux resoudre ce probleme

**Comment by DarkShadowZZ** [comment]
FIXES #1

**Comment by DarkShadowZZ** [comment]
je peux resoudre ce probleme
